import NavBar from "./components/NavBar";
import "./globals.css";
import AuthProvider from "./components/authProvider";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <NavBar />
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
